version: "3.8"  

services:
  model_optimization:
    build: model_optimization
    volumes:
      - ./model_optimization/data:/app/data  
      - ./model_optimization/models:/app/models
      - ./model_optimization/mlflow.db:/app/mlflow.db
    ports:
      - "5000:5000"
    tty: true


  model_deployment:
    build: model_deployment
    volumes: 
      - ./model_deployment/models:/app/models
    ports:
      - "8000:8000"
    tty: true
      

  